#!/usr/bin/bash

# SCRIPT=$(realpath "$0")
# SCRIPTPATH=$(dirname "$SCRIPT")

NETEDIT_PORT=11110

while [ $# -ge 1 ]; do
  case $1 in
  start)
    # Setup DNAT for netedit for locally generated packets
    # Note the PREROUTING chain isn't used as it doesn't apply to locally generated packets.
    # If one wants to do DNAT using the local computer to forward packets (which also requires the PREROUTING chain), enable ip forwarding:
    # $ sysctl net.ipv4.conf.<interface>.forwarding=1

    iptables -t nat -D OUTPUT -p tcp ! --sport $NETEDIT_PORT --dport 80 -j REDIRECT --to-ports $NETEDIT_PORT
    # iptables -t nat -D OUTPUT -p tcp ! --sport $NETEDIT_PORT --dport 443 -j REDIRECT --to-ports $NETEDIT_PORT

    # Redirect packets generated by local interface to netedit, avoiding redirecting netedit back to itself
    iptables -t nat -I OUTPUT -p tcp ! --sport $NETEDIT_PORT --dport 80 -j REDIRECT --to-ports $NETEDIT_PORT
    # iptables -t nat -I OUTPUT -p tcp ! --sport $NETEDIT_PORT --dport 443 -j REDIRECT --to-ports $NETEDIT_PORT
    iptables -t nat -L -n -v
    ;;

  stop)
    iptables -t nat -D OUTPUT -p tcp ! --sport $NETEDIT_PORT --dport 80 -j REDIRECT --to-ports $NETEDIT_PORT
    # iptables -t nat -D OUTPUT -p tcp ! --sport $NETEDIT_PORT --dport 443 -j REDIRECT --to-ports $NETEDIT_PORT
    ;;

  list)
    iptables -t nat -L -v -n
    ;;

  # backup)
  #   iptables-save >"${SCRIPTPATH}/iptables.conf"
  #   ip6tables-save >"${SCRIPTPATH}/ip6tables.conf"
  #   ;;

  # restore)
  #   iptables-restore <"${SCRIPTPATH}/iptables.conf"
  #   ip6tables-restore <"${SCRIPTPATH}/ip6tables.conf"
  #   ;;

  # reset)
  #   # clear iptables tables
  #   iptables -P INPUT ACCEPT
  #   iptables -P FORWARD ACCEPT
  #   iptables -P OUTPUT ACCEPT

  #   iptables -Z
  #   for table in filter nat mangle raw; do
  #     iptables -t $table -F
  #     iptables -t $table -X
  #   done
  #   ;;

  # start)
  #   # backup
  #   iptables-save >"${SCRIPTPATH}/iptables.conf"
  #   ip6tables-save >"${SCRIPTPATH}/ip6tables.conf"

  #   # netedit
  #   iptables -t nat -I OUTPUT -p tcp ! --sport $NETEDIT_PORT --dport 80 -j REDIRECT --to-ports $NETEDIT_PORT
  #   # iptables -t nat -I OUTPUT -p tcp ! --sport $NETEDIT_PORT --dport 443 -j REDIRECT --to-ports $NETEDIT_PORT
  #   iptables -t nat -L -n -v
  #   ;;

  help | -h | --help) ;&
  *)
    echo "bash iptables.sh start|stop|list"
    ;;
  esac

  shift
done
